dist: trusty
sudo: false
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
  - $HOME/Library/Caches/Homebrew
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - COMPILER="4.05.0"
  - OPAMYES=true
matrix:
  fast_finish: true
os:
    - linux
    - osx

before_install:
    if [ $TRAVIS_OS_NAME = osx ]; then
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -;
    rvm get stable;
    brew update; brew install opam; fi

install:
- "[ -e .opam ] || travis_wait opam init -j ${NJOBS} --compiler=${COMPILER} -n -y"
- eval $(opam config env)
- opam config var root
- opam repo add coq-released https://coq.inria.fr/opam/released || true
- opam list
- ocamlc -v

script:
- set -e
- echo 'Building QuickChick...' && echo -en 'travis_fold:start:QuickChick.build\\r'
- opam update
- travis_wait 30 opam install coq-mathcomp-ssreflect.1.6.2
- make -j install
- cd examples/multifile-mutation && make && quickChick -top Top
- echo -en 'travis_fold:end:QuickChick.build\\r'
