version: 2.1

defaults: &defaults
  environment:
    OPAMJOBS: 2
    OPAMVERBOSE: 1
    OPAMYES: true
    TERM: xterm
  steps:
  - startup
  - build

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
  build:
    steps:
    - run:
        name: Install dependencies
        command: opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list
    - run:
        name: Building QuickChick
        command: opam install .
    - run:
        name: Unit testing
        working_directory: test
        command: make -j`nproc`
    - run:
        name: Testing IFC
        working_directory: examples/ifc-basic
        command: make -j`nproc`
    - run:
        name: Testing Red-black tree
        working_directory: examples/RedBlack
        command: make -j`nproc`
    - run:
        name: Testing STLC
        working_directory: examples/stlc
        command: make -j`nproc`
    - run:
        name: Testing Multifile Mutation
        working_directory: examples/multifile-mutation
        command: make -j`nproc` test
    - run:
        name: Testing C Mutation
        working_directory: examples/c-mutation
        command: make -j`nproc` lesstest
    - run:
        name: Testing Python I/O
        working_directory: examples/python-io
        command: make -j`nproc` lesstest
    - run:
        name: Removing QuickChick
        command: opam remove .
jobs:
  ocaml 4_05:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.8
  ocaml 4_09:
    <<: *defaults
    docker:
    - image: coqorg/coq:8.8-ocaml-4.09.0-flambda

workflows:
  version: 2
  build:
    jobs:
    - ocaml 4_05
    - ocaml 4_09
