version: 2.1

defaults: &defaults
  environment:
    OPAMJOBS: 2
    OPAMVERBOSE: 1
    OPAMYES: true
    TERM: xterm
  docker:
  - image: coqorg/coq:8.7

commands:
  startup:
    steps:
    - checkout
    - run:
        name: Configure environment
        command: echo . ~/.profile >> $BASH_ENV
  build:
    steps:
    - run:
        name: Install dependencies
        command: opam install --deps-only .
    - run:
        name: List installed packages
        command: opam list
    - run:
        name: Building QuickChick
        command: opam install coq-quickchick .
    - run:
        name: Unit testing
        working_directory: test
        command: make -j`nproc`
    - run:
        name: Testing IFC
        working_directory: examples/ifc-basic
        command: make -j`nproc`
    - run:
        name: Testing Red-black tree
        working_directory: examples/RedBlack
        command: make -j`nproc`
    - run:
        name: Testing STLC
        working_directory: examples/stlc
        command: make -j`nproc`
    - run:
        name: Testing Multifile Mutation
        working_directory: examples/multifile-mutation
        command: make -j`nproc` test
    - run:
        name: Testing C Mutation
        working_directory: examples/c-mutation
        command: make -j`nproc` test
jobs:
  ocaml 4_05:
    <<: *defaults
    steps:
    - startup
    - build
  ocaml 4_07:
    <<: *defaults
    steps:
    - startup
    - run: opam switch 4.07.1+flambda
    - build

workflows:
  version: 2
  build:
    jobs:
    - ocaml 4_05
    - ocaml 4_07
